name: Run Postman API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: | 
         npm install -g newman
         npm install -g newman-reporter-html

      - name: Run Postman Tests
        run: |
          newman run postman/apitest.json \
          --reporters cli,html \
          --reporter-html-export newman-report.html
          
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: newman-report.html
      
      
